# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U3a_Q8R953MJcbKWbB2dKkHCdHscmtJJ
"""

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

x = 1
if x==1: data = np.genfromtxt("/content/drive/MyDrive/Colab Notebooks/passenger_car.csv", delimiter=",")
elif x==2: data = np.genfromtxt("/content/drive/MyDrive/Colab Notebooks/motorcycle.csv", delimiter=",")
elif x==3: data = np.genfromtxt("/content/drive/MyDrive/Colab Notebooks/truck.csv", delimiter=",")
# Columns has headings: [YOLO distance, Carla distance, Predicted vehicle, Expected output, Testing]

data = data[1:] # Removing the headers
sorted_data = sorted(data, key=lambda a_entry: a_entry[0]) 
sorted_data = np.array(sorted_data)

# train, test = train_test_split(data, test_size=0.2, random_state=30)

# # TRAINING DATA
# # Getting expected distance
# x_train = np.array([train[x][0] for x in range(len(train))]).reshape(-1,1)
# # Getting YOLO distance
# y_train = np.array([train[x][3] for x in range(len(train))])

# # TESTING DATA
# # Getting expected distance
# x_test = np.array([test[x][0] for x in range(len(test))]).reshape(-1,1)
# # Getting YOLO distance
# y_test = np.array([test[x][3] for x in range(len(test))])

x_train = sorted_data[:,0][::3].reshape(-1,1)
y_train = sorted_data[:,3][::3]

x_test = sorted_data[:,0][::2].reshape(-1,1)
x_test = x_test[::4]
y_test = sorted_data[:,3][::2]
y_test = y_test[::4]

model = LinearRegression().fit(x_train, y_train)
y_pred = model.predict(x_test)

print(np.var(y_pred-y_test))

print(mean_squared_error(y_pred, y_test))

import matplotlib.pyplot as plt

plt.scatter(x_train, y_train)
plt.plot(x_test, y_pred, color='red')
plt.title("For PassengerCar")
plt.xlabel("Estimated distance")
plt.ylabel("Carla ground truth distance")
plt.legend(['Model fitted line', 'Training data'])
plt.show()

